In [1]:
# load the iris dataset as an example 
from sklearn.datasets import load_iris
iris = load_iris()

# store the feature matrix (X) and response vector (y) 
X = iris.data
y = iris.target

# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)

# training the model on training set 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# making predictions on the testing set 
y_pred = knn.predict(X_test)

# comparing actual response values (y_test) with predicted response values (y_pred) 
from sklearn import metrics
print("kNN model accuracy:", metrics.accuracy_score(y_test, y_pred))

# making prediction for out of sample data 
sample = [[3, 5, 4, 2], [2, 3, 5, 4]]
preds = knn.predict(sample)
pred_species = [iris.target_names[p] for p in preds]
print("Predictions:", pred_species)

# saving the model 
from sklearn.externals import joblib
joblib.dump(knn, 'iris_knn.pkl')


kNN model accuracy: 0.9833333333333333
Predictions: ['versicolor', 'virginica']


['iris_knn.pkl']

In [8]:
import numpy
filename = 'C:/Users/prana/Documents/risk-prediction-data.csv'
raw_data = open(filename, 'rt')
data = numpy.loadtxt(raw_data, delimiter=",")
print(data)
print(data.shape)

X = data[1:, 1:3] # we only take the first two features. 
#Y = target
print(X)

[[ 1.  2.  3.  4. 11.]
 [ 1.  2.  4.  4. 12.]]
(2, 5)
[[2. 4.]]


In [ ]:
import numpy
mylist = [[1, 2, 3], [3, 4, 5]]
myarray = numpy.array(mylist)


print("Whole col: %s") % myarray[:, 2]